export const LOGIN_USER = 'LOGIN_USER',
             LOGOUT_USER = 'LOGOUT_USER',

             GET_PEDIDOS = "GET_PEDIDOS",
             GET_PEDIDO = "GET_PEDIDO",
             LIMPAR_PEDIDO = "LIMPAR_PEDIDO",
             CANCELAR_PEDIDO = "CANCELAR_PEDIDO",
             
             GET_CLIENTES = "GET_CLIENTES",
             GET_CLIENTE = "GET_CLIENTE",
             GET_CLIENTE_PEDIDOS = "GET_CLIENTE_PEDIDOS",
             REMOVE_CLIENTE = "REMOVE_CLIENTE",
             LIMPAR_CLIENTE = "LIMPAR_CLIENTE",
             
             GET_CATEGORIAS = "GET_CATEGORIAS",
             GET_CATEGORIA = "GET_CATEGORIA",
             LIMPAR_CATEGORIA = "LIMPAR_CATEGORIA",
             REMOVE_CATEGORIA = "REMOVE_CATEGORIA",
             GET_CATEGORIA_PRODUTOS = "GET_CATEGORIA_PRODUTOS",
             
             GET_PRODUTOS = "GET_PRODUTOS",
             GET_PRODUTO = "GET_PRODUTO",
             LIMPAR_PRODUTO = "LIMPAR_PRODUTO",
             
             GET_VARIACOES = 'GET_VARIACOES',
             GET_VARIACAO = 'GET_VARIACAO',
             LIMPAR_VARIACAO = 'LIMPAR_VARIACAO',
             REMOVE_VARIACAO = 'REMOVE_VARIACAO',
             
             GET_AVALIACOES = 'GET_AVALIACOES',
             GET_AVALIACAO = 'GET_AVALIACAO',
             LIMPAR_AVALIACAO = 'LIMPAR_AVALIACAO',
             REMOVE_AVALIACAO = 'REMOVE_AVALIACAO',
             
             GET_CONFIGURACOES = "GET_CONFIGURACOES",
             LIMPAR_CONFIGURACOES = 'LIMPAR_CONFIGURACOES';